### ISSUE TITLE
Malformed sfx triggers uncaught "TypeError" in browser console

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#101]
**Reproduction Steps**
1. Launch https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
2. Open browser console
3. Add any non-numeric character to the end of an sfx line (e.g. ';' or 'q')
4. click on the line to hear the sfx 
5. An uncaught "TypeError" is observed in console
6. Further edits of the same line are now difficult (back out the change using CTRL-Z)

**What did you expect would happen?**
No crash - editor stays responsive

**OS & Browser version, desktop/mobile**
MAC/Desktop/Chrome (also observed with FireFox)

**Screenshots, example projects, other relevant issues, etc.**
<img width="799" alt="Screenshot 2024-09-07 at 11 53 03" src="https://github.com/user-attachments/assets/accccd2a-ab0d-41d3-ab44-5ab6e8e2a75a">

**Comment by angilbert** [comment]
Looks to be a regression issue on dev-release. Stable release is fine.

**Comment by david-pfx** [comment]
Thanks! The real bug is that it doesn't detect the error. Fixed.
