### ISSUE TITLE
Transform of translate:up:X works in P:S, not here

### ISSUE THREAD

**Issue by david-pfx** [david-pfx/PuzzleScriptNext#102]
cool nico: compare this example in [Pattern:Script](https://clementsparrow.github.io/Pattern-Script/src/editor.html?hack=e402f0f2ac6a5ac82ef38fced681dca1) with the exact same example in [PuzzleScript Next](https://puzzlescriptnext.polyomino.com/editor.html?hack=e402f0f2ac6a5ac82ef38fced681dca1) which won't work.

**Comment by david-pfx** [comment]
Also https://clementsparrow.github.io/Pattern-Script/src/editor.html?hack=09506b3fbeccc53e0ac6d404b57d1a64

**Comment by david-pfx** [comment]
Docs here: https://github.com/ClementSparrow/Pattern-Script/wiki#sprite-copy-and-transformations

**Comment by angilbert** [comment]
I think this is the same issue as: https://github.com/david-pfx/PuzzleScriptNext/issues/65

**Comment by david-pfx** [comment]
Actually, it's not. This translate amounts not allowing a tag/mapping.

**Comment by david-pfx** [comment]
Fixed. Probably still some gaps in handling of mappings
