### ISSUE TITLE
A "maximum operations limit" prelude

### ISSUE THREAD

**Issue by just-kirb** [david-pfx/PuzzleScriptNext#104]
Check ([ ] -> [x]) all that apply, then describe the issue below:

- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)
Problem:
Of course, a game cannot tell when it will halt or not. However, sometimes the game would automatically end the operations even if the script is likely to halt. An example is trying to implement a rule in puzzlescript that requires lots of loops and rules due to its complexity. see: https://puzzlescriptnext.polyomino.com/editor.html?hack=258d8a90274915a388b0738872c2e2f5 in Not The Witness Triangles 2nd level.
Proposal:
Add a prelude called "maximumoperations". It changes the amount of "operations" allowed within some frame of code before it immediately halts the program. This allows to fix the problem for a long operation needing to take place without it halting.

**Comment by david-pfx** [comment]
Is this just to tweak the 200 limit on looping, or something else?

**Comment by just-kirb** [comment]
tweaking looping, maybe tweaking the maximum amount of operations if needed

**Comment by david-pfx** [comment]
You're going to have to a bit more specific. PS has 4 different kinds of looping. Can you post the error message, and the line(s) of code that trigger it?

**Comment by just-kirb** [comment]
https://puzzlescriptnext.polyomino.com/play.html?p=258d8a90274915a388b0738872c2e2f5

**Comment by david-pfx** [comment]
So that's the program. Good start. Looks interesting. Now a repro case needs 3 more things:
1. What should I input to show the problem?
2. What will I see (caused by the problem)?
3. What should I see (if the problem was fixed)?

**Comment by david-pfx** [comment]
OK, repro. It's the STARTLOOP error, not one of the others. And raising the limit is not going to help -- I tried it. Did you read the section here: http://localhost:8020/src/Documentation/executionorder.html?

"To be clear: if any rule in any rule-group within a startloop/endloop block makes any changes to objects/movements, the loop will repeat."

You need to make your program so it doesn't do that.

**Comment by just-kirb** [comment]
sorry if i wasted your time, but yeah, i did resolve the problem via making
simpler code that can run the program with reduced capabilities

**Comment by david-pfx** [comment]
No problem. Just let me know if you have any other problems. Or just ask on the  Discord Thinky Games channel (link at the top of the documentation pages).
