### ISSUE TITLE
Add mappings to sprite modifiers

### ISSUE THREAD

**Issue by Nickneim** [david-pfx/PuzzleScriptNext#105]
- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

To add to #102, Pattern:Script allows usage of Mappings inside modifiers themselves (translate, shift, etc). This could also be added to PuzzleScript Next.

This [example in Pattern:Script](https://clementsparrow.github.io/Pattern-Script/src/editor.html?hack=d7cd81b87d7403ced7e4e47389842bf1) maps both a direction and an amount in a translate statement, neither of which work. Here is the same [example in PuzzleScript Next](https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?hack=d7cd81b87d7403ced7e4e47389842bf1). I have commented out 3 other more simple options for the translate statement, only one of which works.

~~I have not done extensive testing of this but weirdly it already works correctly for `rot`, so maybe this issue is not an enhancement but rather a bug.~~ Edit: Nevermind, it doesn't work correctly.

**Comment by david-pfx** [comment]
It crashes. It's a bug. Will fix.

**Comment by david-pfx** [comment]
Done. v-24i15
