### ISSUE TITLE
Canvas example project Wriggle does not render correctly (dev-release)

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#109]
**Describe the bug**
Example project Wriggle is currently not fully working on dev-release

**Reproduction Steps**
1. Launch https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
2. Select Wriggle (Example project) and load the first level

This URL does the same, but uses the source GIST: https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?hack=3c6b8078c4b48b814fcaa05f09368364

**What did you expect would happen?**
The background grid would appear and the wriggler would be rendered in blue - as it does when I test it using the old "canvasy" dev branch

**OS & Browser version, desktop/mobile**
MAC/Chrome/Desktop - and others

**Screenshots, example projects, other relevant issues, etc.**
A screenshot comparing "canvasy" branch (left) with current dev-release (right)

<img width="1765" alt="Screenshot 2024-09-29 at 10 00 48" src="https://github.com/user-attachments/assets/763d2762-f6dc-49c8-9058-88d179b67366">

**Comment by david-pfx** [comment]
Regression caused by #105. Fixed.
