### ISSUE TITLE
Rules that trigger "again" end afx transitions

### ISSUE THREAD

**Issue by rolopogo** [david-pfx/PuzzleScriptNext#110]
**Describe the bug**
Rules that trigger "again" end afx transitions

**Reproduction Steps**
1. Moving object with a ``move afx:...`` effect
2. A rule that calls "again"

**What did you expect would happen?**
Expect player to move smoothly, but player moves instantly.

**OS & Browser version, desktop/mobile**
Browser

**Screenshots, example projects, other relevant issues, etc.**
Repro save.
```title again afx tweens
author rolopogo

level_select
run_rules_on_level_start
again_interval 0
animate_interval 0.25
verbose_logging


========
OBJECTS
========

player
green

background
black

=======
LEGEND
=======

. = background
p = player

=======
SOUNDS
=======

player move afx:slide

================
COLLISIONLAYERS
================

background
player

======
RULES
======

[moving player] -> again

==============
WINCONDITIONS
==============


=======
LEVELS
=======

section level
.....
.....
..p..
.....
.....```

**Comment by david-pfx** [comment]
I think what you're asking for is that the `again` cycle does not start until the animation is complete. They can't run at the same time.

**Comment by rolopogo** [comment]
I fixed it in https://github.com/david-pfx/PuzzleScriptNext/pull/111 by directly reverting the changes made by the dry run.
 
However, delaying the execution of again seems much more maintainable vs ensuring no changes happen during the dry run of the rules. What would happen when again_interval is less than animation time?

**Comment by david-pfx** [comment]
I had in mind to replace line 1455 in inputoutput.js:
`        if (timer>againinterval && messagetext == "") {`
by
`        if (timer>againinterval && messagetext == "" && !isAnimating) {`
and see if that fixes it.

**Comment by david-pfx** [comment]
Fixed. Same idea as #111 but different place for code.
