### ISSUE TITLE
Create and destroy sounds and animations play even if the object is destroyed immediately

### ISSUE THREAD

**Issue by rolopogo** [david-pfx/PuzzleScriptNext#113]
**Describe the bug**
Create effects are played for objects that are immediately destroyed
Destroy effects are played for newly created objects that are destroyed

This doesn't feel intuitive, though could be used on purpose for creating temporary animated effects.

Suggestion: if an object is created and destroyed in the same frame, neither effect is played, as if it never existed.

**Reproduction Steps**
1. Have a rule create an object, and another destroy it immediately
2. Have a sound attached for creation and/or destruction of that object

**What did you expect would happen?**
No sound plays if an object is created and destroyed in the same frame

**OS & Browser version, desktop/mobile**
Browser

**Screenshots, example projects, other relevant issues, etc.**
```title Create/destroy sounds
author rolopogo
homepage www.polyomino.com

// 

smoothscreen 5x5

========
OBJECTS
========

Background 
black

Player; #00f8
Crate; orange

=======
LEGEND
=======

. = Background
P = Player
* = Crate

=======
SOUNDS
=======

crate create 45612500
crate destroy afx:turn

================
COLLISIONLAYERS
================

Background
Player
Crate

======
RULES
======

[ >  Player ] -> [  >  Player Crate  ]
[Crate] -> []

==============
WINCONDITIONS
==============


=======
LEVELS
=======
section 1
.....
.....
..p..
.....
.....
```

**Comment by david-pfx** [comment]
Really not sure about this one. For one thing, I would expect the same issue applies to sound effects already. For another, not easy to do for not much benefit.

Main problem is how to do it. Maybe go through all the sound/animation effects for an object and get rid of some combos? Needs lots of testing I think.

**Comment by rolopogo** [comment]
Recommend if an object is destroyed it cannot play other animations or sounds, if it is in both created and destroyed, it doesn't play any.My justification is that the animations and sounds play for state changes from turn start to turn end, rather than any intermediate changesOn 25 Oct 2024 07:24, david-pfx ***@***.***> wrote:
Really not sure about this one. For one thing, I would expect the same issue applies to sound effects already. For another, not easy to do for not much benefit.
Main problem is how to do it. Maybe go through all the sound/animation effects for an object and get rid of some combos? Needs lots of testing I think.

**Comment by david-pfx** [comment]
On the basis of the difficulty, minimal benefit and loss of PS compatibility, I'll pass on this one.
