### ISSUE TITLE
level_select_lock does not work

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#114]
**Describe the bug**
The level_select_lock prelude option does not lock future levels. The level names are hidden, but can still be selected/played.

**Reproduction Steps**
1. Load an example game with level_select enabled (e.g. Wriggle)
2. Add "level_select_lock" to the prelude
3. Save/run the game, go to the level select screen and try to select a locked level
4. The level loads and runs

**What did you expect would happen?**
The level should not load (see PS+ behaviour)

**OS & Browser version, desktop/mobile**
Desktop/MAC/Chrome (and same on Firefox)

**Screenshots, example projects, other relevant issues, etc.**
Problem exhibits on both stable and dev release
There are no errors in browser console
Adding "level_select_unlocked_ahead" makes no difference (although it does hide the correct number of level names)

**Comment by angilbert** [comment]
Example game "Gridlocked" will also demonstrate this issue without any source changes required because it already uses level_select_lock.

**Comment by david-pfx** [comment]
Fixed. Couple of lines got left out during a merge.
Note there were differences between keyboard and mouse.
