### ISSUE TITLE
Ability to use an emoji for a sprite's image

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#115]
Suggested syntax:
```
Crate
emoji: 📦

Clown
emoji: 🤡

Cake
emoji: 🎂
```

During prototyping, this would be useful for quickly creating placeholder objects that are readable as a specific thing.

For full games, this would allow for a visual style that's easy to achieve but distinct from most existing PuzzleScript games.

- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

**Comment by angilbert** [comment]
It's not documented, but you can already achieve this using text sprites. You can also scale the size of the sprite. You have to supply a colour, but it's ignored. Here's an example... 

star * scale:0.6
red; text: ⭐

**Comment by angilbert** [comment]
Another way to achieve the same thing is using canvas sprites which also allows you to apply sprite transforms. A few examples can be found here: https://puzzlescriptnext.polyomino.com/editor.html?hack=2f89eb3afb3192b1d17a27d94c376c4a

**Comment by david-pfx** [comment]
I'm inclined to think this is enough.

**Comment by angilbert** [comment]
Unfortunately the "text" example quoted above no longer works on dev-release. See: https://github.com/david-pfx/PuzzleScriptNext/issues/117

**Comment by david-pfx** [comment]
Fixed. Looks done to me.
