### ISSUE TITLE
require_player_movement + run_rules_on_level_start + goto is incompatible

### ISSUE THREAD

**Issue by just-kirb** [david-pfx/PuzzleScriptNext#116]
**Describe the bug**
require_player_movement + run_rules_on_level_start + goto is incompatible as trying to enter a level with goto in the 2 preludes involved would only lead to staying in the level, with buggy side effects of the camera.

**Reproduction Steps**
1. Have all require_player_movement + run_rules_on_level_start + goto (within the rules) in 1 game
2. meet the GOTO requirement
3. The game would have a behavior that would adjust the camera dimensions of the proceeding level, but keep the 1st level as its base

**What did you expect would happen?**
The GOTO would proceed as normal, bringing the game to the next level without undoing the idle move at the start of the level

**OS & Browser version, desktop/mobile**
Windows 10
Firefox Version 131

**Screenshots, example projects, other relevant issues, etc.**
[Link to game](https://puzzlescriptnext.polyomino.com/editor.html?hack=5114fd96cc01aeda9986956eba282448)

**Comment by david-pfx** [comment]
If you set `verbose_logging` you can see what's happening. It's applying `require_player_movement` when it should not.

**Comment by david-pfx** [comment]
After a good look at the code, it's a miracle it works as well as it does. It's an old bug: https://auroriax.github.io/PuzzleScript/play.html?p=5114fd96cc01aeda9986956eba282448. 

Basically it switches to the new level while still processing the old one, and relies on nothing else happening to sort things out at the end of turn.

There may be a quick fix, dunno yet.

**Comment by david-pfx** [comment]
Fixed. Will need testing to make sure nothing else broke.
