### ISSUE TITLE
Text sprites broken on dev release

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#117]
**Describe the bug**
dev-release browser crashes if you try to add a text sprite with scale applied

**Reproduction Steps**
1. Load https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
2. Open the browser console
3. Select the example blank project
4. Cut and paste the following sprite as a new object...

star * scale:0.6
red; text: ⭐

**What did you expect would happen?**
Dev-release should behave like stable release. 

On stable release the use of ";" triggers a red warning/error - but this can be fixed by adding a "//" comment to the prelude, or by adding a line-break instead. 

**OS & Browser version, desktop/mobile**
MAC/Chrome/Desktop

**Screenshots, example projects, other relevant issues, etc.**
The problem is not specific to use of emoji - a text string triggers the same issue. It appears to be the use of "scale:" that trips up the parser. 

<img width="435" alt="Screenshot 2024-10-24 at 09 59 35" src="https://github.com/user-attachments/assets/49eafd25-93ee-465f-9de8-8071c3576830">

**Comment by david-pfx** [comment]
Fixed.
