### ISSUE TITLE
Support non-square sprite sizes

### ISSUE THREAD

**Issue by rolopogo** [david-pfx/PuzzleScriptNext#119]
Check ([ ] -> [x]) all that apply, then describe the issue below:

- [ x ] I have searched the tracker for similar issues (including closed ones)
- [ x ] I have provided a detailed example for how this feature should work
- [ x ] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

The prelude `sprite_size AxB` only creates AxA grid cells. More control over grid size and spacing would allow more flexibility for creators.
This is particularly useful when rendering with perspective, where forshortening along the up axis enhances the illusion of a lowered camera.

sprite_size 16x16
![image](https://github.com/user-attachments/assets/753eb1c9-d0f7-46a3-8443-740b13445381)

sprite_size 16x10
![image](https://github.com/user-attachments/assets/8a0b944e-b1db-412c-96c1-46de95753362)

**Comment by david-pfx** [comment]
I've wondered about this. Text mode cells are not square, so most of the code already handles it. I'll have a look at what's involved.

I assume you would use it for your game?

**Comment by rolopogo** [comment]
I'm already using this in my forklift version for 16x10 sprites with a bunch of translates for elevation.

**Comment by david-pfx** [comment]
Done.
