### ISSUE TITLE
status_line updates are flushed by use of "again"

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#122]
**Describe the bug**
The documentation states that status messages remain in place until cleared by another status line update - but this is not true. Use of "again" seems to be enough to flush the message. This behaviour renders the status_line feature useless in the any games that use "again". 

**Reproduction Steps**
1. Try: https://puzzlescriptnext.polyomino.com/play.html?p=2af7291a0675f386e320a53a2aaf7107
2. Move... URULD (to sink a black ball)
3. A status message "Black ball sunk!" will flash briefly and then disappear (don't blink!)

**What did you expect would happen?**
The message "Black ball sunk!" should remain in situ 

**OS & Browser version, desktop/mobile**
MAC/Chrome/Desktop (but not specific)

**Screenshots, example projects, other relevant issues, etc.**
Problem can be reproduced on stable and dev-releases

There is no rule here to clear the status message - so it should persist...
<img width="514" alt="Screenshot 2024-10-28 at 14 36 36" src="https://github.com/user-attachments/assets/47ec1767-5d65-4a42-bb88-982526048ef1">

**Comment by angilbert** [comment]
Use of "again" is just one of many issues here. I have raised two other issues and could raise more. Basically status_line is not fit for purpose at the moment.

**Comment by david-pfx** [comment]
I have to agree. To date, it hasn't attracted a lot of interest so the priority has been low. Nothing like raising an issue with a repro to pique my interest!

**Comment by david-pfx** [comment]
I've been focussed on the non-square and related, but I do intend to fix those status things. Overdue.

**Comment by david-pfx** [comment]
Fixed. But please note, the intended behaviour is that the status line is cleared by the next user input. Docs updated to match.
