### ISSUE TITLE
Undo does not rewind the status message

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#123]
**Describe the bug**
The status message needs to be stored as part of state so it can be updated/reverted on undo. Currently the status message is untouched if you hit undo to rewind time. 

**Reproduction Steps**
Play example game "Fifteen" until you see the win message - then undo a move. The status line is not reverted. 

**What did you expect would happen?**
The previous state is fully reinstated on undo - including the status line.

**Screenshots, example projects, other relevant issues, etc.**

<img width="469" alt="Screenshot 2024-10-28 at 16 57 40" src="https://github.com/user-attachments/assets/1fbf4650-b7f5-483b-846c-a5d17c47e974">

**Comment by david-pfx** [comment]
Fixed. 
Please note there is a test level, with just one move to win.
