### ISSUE TITLE
Use of zoomscreen breaks status_line

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#124]
**Describe the bug**
Use of zoomscreen breaks status_line

**Reproduction Steps**
1. Launch the PS editor and load example game Fifteen
2. Add "zoomscreen 8x8" to prelude - save and run
3. Win the game - there is no Win message (but verbose logging indicates the status rule has triggered)

**What did you expect would happen?**
Win message should appear in the status line

**OS & Browser version, desktop/mobile**
All

**Screenshots, example projects, other relevant issues, etc.**
Notice that rule 127 has triggered but there is no message...
<img width="651" alt="Screenshot 2024-10-28 at 17 40 49" src="https://github.com/user-attachments/assets/72cda882-c5d8-4e90-ba41-906c95494aab">

**Comment by david-pfx** [comment]
Can no longer repro after fixing #122, #123.

**Comment by angilbert** [comment]
This is still broken on dev-release. Status line messages do not appear if zoomscreen is enabled (it doesn't work for flickscreen either). The steps above reproduce the issue. I've tested both Chrome and Firefox on MAC. There are no errors in browser console. I'm not sure how to re-open the bug.

**Comment by david-pfx** [comment]
Oops. Repro. Reopened.

**Comment by david-pfx** [comment]
It's a problem with my test program. The status line works just fine as long as the level fills the zoom/cflickscreen size, but if not it gets clipped out. Try `zoomscreen 6x6`.
Will fix.

**Comment by david-pfx** [comment]
Fixed.

**Comment by angilbert** [comment]
I assume I can't test this yet. Let me know when I can. Have you also checked the status_line is consistently displayed below the play grid? I attach a video demonstrating the status_line overlaying the level itself when the H value for smoothscreen is set smaller than the level height (see the final SAVE/RUN in the video).

https://github.com/user-attachments/assets/ffb54123-5883-4250-9a52-37c3c082cf59

**Comment by david-pfx** [comment]
This appears to be a new issue specific to `smoothscreen`. Happy to look into it.
