### ISSUE TITLE
Support loading images via URL

### ISSUE THREAD

**Issue by IrregularHex** [david-pfx/PuzzleScriptNext#129]
Check ([ ] -> [x]) all that apply, then describe the issue below:

- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

I wanted to add support for using full resolution images / spritesheets. A simple way to get this working was to support loading and drawing from a URL like this:
```
load_images my_sprites=https://[...]/sprites.png

========
OBJECTS
========
Player canvas:
{"drawImage":["my_sprites",   0,   0, 64, 64, 0, 0, 1, 1]}
```

- Demo of this working: https://irregularhex.itch.io/van-gogh-slide?secret=RWSWjD3hYn7ThSV349gt2BHMnM
- Demo source (it won't compile without my changes, but you can see what the syntax is like) https://puzzlescriptnext.polyomino.com/editor.html?hack=66dd8eb43de34db8f5be192942c25678
- Branch: https://github.com/IrregularHex/PuzzleScriptNext-testing/commits/image_urls

I based the `load_images` command on how `custom_font` currently works, and I special-cased the canvas `drawImage` command to use the images you loaded earlier (currently any drawImage command fails with an error because the image argument is passed as a string).

The main downside of this approach is that you have to host the images online somewhere. If you try to load them from a local file, Chrome will give you a CORS error (anecdotally, Safari seems to be less picky). One solution is to upload the images to a GitHub repo, or you also could try running a local server which sets the right CORS headers for images (Python's simple HTTP server does _not_ set these headers, so it doesn't work).

So the workflow is a bit annoying, but it does work :)

An different approach might be to have PuzzleScript pop up a file dialog where you can import your image, and it would be saved to localstorage. Then when you export the game, it would be written back out to an image file next to the html file. This would be a lot harder to implement, though.

**Comment by david-pfx** [comment]
That's cute! Definitely worth doing, if not too hard. Worth a chat on the PSNext thread, and see if anyone else has ideas...

**Comment by david-pfx** [comment]
Accepted. Looks just fine, but I have nothing to test it with. Do you have a test program?

**Comment by IrregularHex** [comment]
Test program:
- https://puzzlescriptnext.polyomino.com/editor.html?hack=66dd8eb43de34db8f5be192942c25678

A couple games I made using this:
- https://irregularhex.itch.io/mux-mahjong [Hack](https://puzzlescriptnext.polyomino.com/editor.html?hack=1675827cd204bbe4de33aa9d7a946168)
- https://irregularhex.itch.io/how-wise-are-the-owls [Hack](https://puzzlescriptnext.polyomino.com/editor.html?hack=5efbad01c08e164ff477d0902a3e12f7)

While making the second one, I realized for pixel art you need to set you need to set `{"imageSmoothingEnabled": false}` or else the sprite looks blurry:
```
Player canvas:
{"imageSmoothingEnabled": false}
{"drawImage":["sprites", 0, 0, 16, 16, 0, 0, 1, 1]}
```
