### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'vector')

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#133]
**Describe the bug**
Defining a new canvas sprite by copying another one that doesn't exist causes a editor crash.

**Reproduction Steps**
Load https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
Load example game ABRACADABRA
change lines 68 so it is a copy of something that doesn't exist. E.g. 

      5 canvas:
      copy: blah

**What did you expect would happen?**
dev-release behaves like stable. Red warning message saying "blah" does not exist.

**OS & Browser version, desktop/mobile**
MAC/Chrome (not relevant)

**Screenshots, example projects, other relevant issues, etc.**
This is a regression issue on dev-release only. 
<img width="1614" alt="Screenshot 2024-11-22 at 11 03 52" src="https://github.com/user-attachments/assets/b9df1531-695f-4017-82af-29bf3f5c67f0">

**Comment by david-pfx** [comment]
Thank you. Reproduced. Fixed.
