### ISSUE TITLE
case_sensitive prelude makes the editor crash

### ISSUE THREAD

**Issue by maximyzer** [david-pfx/PuzzleScriptNext#2]
**Describe the bug**
You can't add "case_sensitive" anymore, the editor crashes

**Reproduction Steps**
1. Try to add case_sensitive to the prelude in any way (auto complete, write is out, paste)

**What did you expect would happen?**
Not crash

**OS & Browser version, desktop/mobile**
Chrome on windows 11

**Comment by david-pfx** [comment]
Oops! It shall be fixed!

What version are you using? The current (unreleased) version doesn't seem to have this problem.

**Comment by maximyzer** [comment]
I'm using the web version here : https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
Should I be using the offline one ?

**Comment by david-pfx** [comment]
Sorry, but it looks like there is something seriously broken. Working on it. Thanks for the heads up.

By all means clone the repo and run in on a local server in the interim.

**Comment by david-pfx** [comment]
New version released. Seems to be fixed. Please check.

**Comment by maximyzer** [comment]
Looks good, thanks a lot !

**Comment by david-pfx** [comment]
Not fixed. Seems to be related to deploying the editor in source. Still investigating.

**Comment by david-pfx** [comment]
Fixed in v-23g08
