### ISSUE TITLE
Crash on browser window resize

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#32]
**Describe the bug**
Crash on browser window resize
In browser console there is... "Uncaught RangeError: Invalid array length" (see screenshot below)

**Reproduction Steps**
1. Launch... https://puzzlescriptnext.polyomino.com/play.html?p=4f8b36f1373d715b7fa47e827c8fef93
2. Start playing the first level and then resize the browser window

**OS & Browser version, desktop/mobile**
Observed in both Safari and Chrome on MAC v14.4 

**Screenshots, example projects, other relevant issues, etc.**
<img width="502" alt="Screenshot 2024-04-22 at 15 24 41" src="https://github.com/david-pfx/PuzzleScriptNext/assets/43546276/32c23b1b-3143-471c-a010-72d02fe63497">

**Comment by david-pfx** [comment]
Confirmed.

**Comment by david-pfx** [comment]
Fixed. Dumb bug.
