### ISSUE TITLE
Sprite transform display anomaly (P:S versus PS>)

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#33]
**Describe the bug**
Compare these two renditions of the same game:
https://clementsparrow.github.io/Pattern-Script/src/play.html?p=b81a790a66fda61d8192888ca2da072d
https://puzzlescriptnext.polyomino.com/play.html?demo=patt/hat_tricks
Something is awry in the PSNext rendition of the AX group of tagged objects (see screenshot below)

**Reproduction Steps**
Use URLs above

**What did you expect would happen?**
The two games should look identical 

**OS & Browser version, desktop/mobile**
MAC Safari & Chrome
I've checked java console - there are no errors reported

**Screenshots, example projects, other relevant issues, etc.**

<img width="650" alt="Screenshot 2024-04-23 at 17 13 53" src="https://github.com/david-pfx/PuzzleScriptNext/assets/43546276/76ef9b5d-019c-4846-8964-593728451ef4">

**Comment by angilbert** [comment]
I correctly guessed the problem. It's because objects A2-A5 do not explicitly state they are copies of A1 (P:S is clearly more forgiving if you do this). It can be easily fixed in the PSNext editor as shown in the screenshot below. This is a very minor anomaly between the two forks, quite possibly not worth fixing. Although I would still recommend updating the GIST used by "play.html?demo=patt/hat_tricks" so the visuals are correct. 

<img width="510" alt="Screenshot 2024-04-23 at 17 22 38" src="https://github.com/david-pfx/PuzzleScriptNext/assets/43546276/4e6b3624-d739-4171-85e8-93c1bb80cc2f">

**Comment by david-pfx** [comment]
Well spotted. I've played that game multiple times and never noticed.
I'll fix it if I reasonably can. It's hard to be sure with some of these, because the 'correct' behaviour of P:S is not defined.

**Comment by david-pfx** [comment]
Fixed in 24e01

**Comment by david-pfx** [comment]
Post vector rewind.
Cannot find any sign it was ever fixed.

**Comment by david-pfx** [comment]
Really fixed in 24f22
