### ISSUE TITLE
Level editor hold down mouse button at edge changes level size multiple times

### ISSUE THREAD

**Issue by Stingby12** [david-pfx/PuzzleScriptNext#44]
**Describe the bug**
If you hold down the mouse button while editing the level, you'll repeatedly change the size of the level. I keep accidentally changing the level size to 1*1 every time I delete an object somewhere.

**Reproduction Steps**
Self-explanatory.

**What did you expect would happen?**
Work like regular PuzzleScript. Even PuzzleScript+ doesn't have this bug either.

**OS & Browser version, desktop/mobile**
Why would you make a PuzzleScript game on mobile ?
Anyways it's the same problem there.

**Comment by david-pfx** [comment]
Sorry, cannot reproduce. Looks like I need those repro steps:

* Specify an example program to load. 
* Specify which keys, click where, hold down which mouse button?
* What will it do? What would you expect it to do?

**Comment by david-pfx** [comment]
Sorry, cannot reproduce. Looks like I need those repro steps:

* Use this release: https://puzzlescriptnext.polyomino.com/editor.html
* Specify an example program to load. 
* Specify which keys, click where, hold down which mouse button?
* What will it do? What would you expect it to do?

**Comment by Stingby12** [comment]
Just hold the mouse button. Literally everytime you are at the edge of the level and you hold it replicates the action.

**Comment by david-pfx** [comment]
So the steps are:
No, nothing like this happens when I try it. Maybe I'm missing a step.
1. Open a game in the editor
2. Run the game
3. Press E to enter level editing mode
4. Click...where exactly? Is the plus sign visible?
5. What happens, exactly?
Would a screenshot showing help?
7.

**Comment by Stingby12** [comment]
I'm going to rewrite everything because reading this again I found a lot of issues. Hopefully this is better to understand.

**Describe the bug**
If you hold down the mouse button while editing the size of the level, you can repeatedly change the size of the level. I keep accidentally changing the level size to 1*1 every time I delete everything in a level or increase the size when I place objects in it.

**Reproduction Steps**
1. Open the level editor on a level.
2. Hold the mouse button on the game screen. Whenever you hold the right click or the left click doesn't matter since it's basically the same results.
3. If you move over the edge of the level (whenever it shows the plus sign) while still holding the mouse button, the level size changes will occur.

**What did you expect would happen?**
I tried on both **PuzzleScript** and **PuzzleScript Plus** and it doesn't seem to happen in here. So I'll just say that what should happen is what should happen when you try that on those two other forks.

**OS & Browser version, desktop/mobile**
Windows 11, Firefox
I also tested on my phone for whatever reason and yeah it's the same exact thing

**Comment by david-pfx** [comment]
Reproduced. The thing you didn't mention was (a) hold down a mouse button (b) move outside the level.

Not obvious how this happens. Will look into it.

**Comment by david-pfx** [comment]
Fixed, indirectly by other and related changes.
