### ISSUE TITLE
Level select + unlocked_rollover + win + goto is broken

### ISSUE THREAD

**Issue by david-pfx** [david-pfx/PuzzleScriptNext#50]
someone1065

https://discord.com/channels/473538592896188446/603626559189942294/1250028801417805939
1) All the levels are unlocked at the start until I beat one of them, at which point they lock other than the first level.
2) Instead of unlocking correctly, they instead unlock in the order that they are placed in the code.
3) The levels unlock not when accessed but when beaten, which means you have to enter a different level and go from there every time you give up.
4) Doing [wincondition]->win goto level A-B doesn't count the level as cleared.

https://puzzlescriptnext.polyomino.com/editor.html?hack=531156b927e868f10093012e130cd0b2

**Comment by someone1065** [comment]
Yeah,

**Comment by david-pfx** [comment]
Sorry, I don't get it. Your example has `level_select_unlocked_rollover 0` -- whatever does that mean?

The code looks the same as PS+ -- does it work differently on PS+? Is this already a PS+ bug?

**Comment by someone1065** [comment]
The intention is for each level to only be unlocked once accessed from another level.

**Comment by david-pfx** [comment]
That's not what it says in the docs: 
https://puzzlescriptnext.polyomino.com/Documentation/prelude.html
https://auroriax.github.io/PuzzleScript/Documentation/prelude.html#psplus

`level_select_unlocked_rollover ` should never be set to zero. That would mean there would be zero unsolved levels visible on level select.

**Comment by someone1065** [comment]
Huh.

**Comment by someone1065** [comment]
So what's the correct flag setup for this then?

**Comment by david-pfx** [comment]
Feature appears to work as documented.
