### ISSUE TITLE
demo=patt/level - compilation error

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#65]
I discovered this by chance. 
I don't think it's related to any recent fixes or feature/branch development...

Try: https://puzzlescriptnext.polyomino.com/editor.html?demo=patt/level
line 180 : You're trying to copy from "WALLDESTROYPATTERN:COUNT:UP" but it's not defined anywhere.

**Comment by david-pfx** [comment]
An object cannot copy from itself.

**Comment by angilbert** [comment]
Feel free to close this as "not a bug", since you closed the loophole in PS> (which i think is sensible). But as a closed issue it is now visible for anyone else who questions it.

**Comment by david-pfx** [comment]
This one is just too hard to figure out how to replace P:S behaviour, for just not enough benefit. So closing as wontfix unless or until someone persuades me otherwise.

**Comment by david-pfx** [comment]
Yes. Now I get it.
