### ISSUE TITLE
visual glitch in editor while editing prelude

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#70]
**Describe the bug**
The editor visually truncates every line below the line you are editing. 

**Reproduction Steps**
Open https://david-pfx.github.io/PuzzleScriptNext/src/editor.html
Select "Fifteen" (example project)
start typing "verbose_logging" into the prelude

**OS & Browser version, desktop/mobile**
MAC/Desktop/Chrome (Edge also)

**Screenshots, example projects, other relevant issues, etc.**

<img width="587" alt="Screenshot 2024-07-25 at 16 29 15" src="https://github.com/user-attachments/assets/92dc316a-0380-4bc7-a9a6-9d3b13dc04be">

**Comment by david-pfx** [comment]
That's horrible. What would make it do that? Seems to be in dev, not stable.

**Comment by david-pfx** [comment]
Fixed. Problem appeared to be failing to parse the whole line after finding an error.
