### ISSUE TITLE
Uncaught exception triggered by LEVEL_EDITOR

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#71]
**Describe the bug**
Uncaught exception if you load a different game while the LEVEL_EDITOR is enabled. The exception fires repeatedly if you move the cursor within the level editor panel.

**Reproduction Steps**
Load https://puzzlescriptnext.polyomino.com/editor.html
Click on LEVEL_EDITOR
Select any other game via "Load" or "Load Examples"

**What did you expect would happen?**
The new game cleanly loads with no crash. 

**OS & Browser version, desktop/mobile**
MAC/Desktop/Chrome
Reproducible in stable and dev-release. 

**Screenshots, example projects, other relevant issues, etc.**

<img width="1197" alt="Screenshot 2024-07-27 at 10 12 49" src="https://github.com/user-attachments/assets/284e7dec-1a7b-4b0c-8da4-71097ca44cdc">

**Comment by david-pfx** [comment]
This bug can be reproduced in original PuzzleScript! The error is different, but the cause is the same: variables not initialised when a new game is loaded.

**Comment by angilbert** [comment]
Closing issue - no fix planned

**Comment by david-pfx** [comment]
Fixed. One liner. Will release shortly.
