### ISSUE TITLE
level-select [NEXT] crash

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#74]
**Describe the bug**
Use of Level-Select [NEXT] triggers a crash on mouse-driven games
UI becomes unresponsive

**Reproduction Steps**
1. Load: https://david-pfx.github.io/PuzzleScriptNext/src/editor.html and open browser console
2. Start playing the example game "Gridblocked" and escape to the level select screen
3. Click on [NEXT] to try to view more levels

**OS & Browser version, desktop/mobile**
Desktop/MAC/Chrome  (also observed on ipad)

**Screenshots, example projects, other relevant issues, etc.**

<img width="1076" alt="Screenshot 2024-07-31 at 16 34 33" src="https://github.com/user-attachments/assets/3dbb1249-e0df-4278-8f9d-bac3194ead76">

**Comment by david-pfx** [comment]
Fixed. Somehow a few lines of really bad code got deleted but not replaced. Big oops.
