### ISSUE TITLE
smoothscreen is broken

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#75]
**Describe the bug**
smoothscreen feature is broken

**Reproduction Steps**
1. load ENIGMASH example project
2. change "zoomscreen" to "smoothscreen"
3. screen goes blank

**Comment by Draknek** [comment]
Shortly after reproducing this in my working project and in ENIGMASH, the browser tab ran out of memory. On reloading the tab it seems to be working as expected. Unsure how to repro this reliably.

**Comment by david-pfx** [comment]
Cannot reproduce. Works fine for me.
https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?demo=plus/enigmash
