### ISSUE TITLE
zoomscreen/flickscreen/etc. shouldn't apply when level editor is active

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#76]
**Reproduction Steps**
1. use zoomscreen feature
2. play a level and press E to use the level editor

**What did you expect would happen?**
When the level editor is active, the entire level should be shown. Otherwise to use the level editor you'd have to disable zoomscreen then rebuild then use the editor then re-enable zoomscreen.

**Comment by david-pfx** [comment]
Yes, I know about this one. At one stage I thought it would be a good idea, perhaps as an option. Right now, I guess it's broken. Should be easy enough to revert. Thanks for noticing.

**Comment by david-pfx** [comment]
Fixed. Will be in next release.

Note: on very large levels like Enigmash it is virtually unusable. Not sure what can be done about that.
