### ISSUE TITLE
Level select should start with the current level selected

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#80]
The level select always seems to open with the very first level selected, but the default selected item should be the current level.

It seems like this could be a regression from PS Plus? I played at least one game which remembered your position (https://pancelor.itch.io/like-a-hot-knife-through-butter)

**Comment by david-pfx** [comment]
I'll take this as a bug.
Fixed. But needs testing.

**Comment by angilbert** [comment]
I can confirm this is fixed on dev-branch. level-select in Wriggle (example project) now launches to display the current-level.
