### ISSUE TITLE
Tapaban (example project) does not visually match the original

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#83]
**Describe the bug**
Compared with https://menderbug.itch.io/tapaban the fade-away outer gridlines do not look right
This is true both on dev-branch and release-branch (so not a regression issue)

**What did you expect would happen?**
The two renditions would look identical

**OS & Browser version, desktop/mobile**
MAC/Desktop/Chrome

**Screenshots, example projects, other relevant issues, etc.**
Original (level 1) : 
<img width="432" alt="Screenshot 2024-08-23 at 16 05 22" src="https://github.com/user-attachments/assets/41d9d640-c9d5-446f-9bb4-fee8dc46146f">
PSNext example project (level 1) : 
<img width="312" alt="Screenshot 2024-08-23 at 16 05 48" src="https://github.com/user-attachments/assets/a40eb10d-26c0-45a3-bc8e-09370fcfa9d4">

**Comment by david-pfx** [comment]
Thanks. I would never have noticed. I wonder what can do that...

**Comment by david-pfx** [comment]
Answer: getting the - and | symbols switched.
Fixed.
