### ISSUE TITLE
Level editor cursor not restricted to level area

### ISSUE THREAD

**Issue by david-pfx** [david-pfx/PuzzleScriptNext#85]
@clickmazes
I tried this... https://david-pfx.github.io/PuzzleScriptNext/src/editor.html?hack=864ec7e3b35626a844b6e292bb5b04b7. And in LEVEL-EDITOR the cursor will list objects below the grid as if there are extra hidden rows. And when I click to place an item it will appear several rows up. Here is a screen shot with the cursor below the grid, but listing objects on the grid (5 rows above).

https://cdn.discordapp.com/attachments/1276344761179050074/1276571753623064586/Screenshot_2024-08-23_at_16.58.53.png?ex=66ca0397&is=66c8b217&hm=322df2d7d7f09b1526182564632e7a925d0aee93966e33094f3708689bbc8ef6&

This does look like a regression issue - because I cannot reproduce the behaviour on stable release. I.e. here... https://puzzlescriptnext.polyomino.com/editor.html?hack=864ec7e3b35626a844b6e292bb5b04b7

**Comment by angilbert** [comment]
This issue doesn't occur on the canvasy branch, so it must be an issue introduced in a very recent update. I might guess the fix for https://github.com/david-pfx/PuzzleScriptNext/issues/76 - because it's in the same area of code.

**Comment by david-pfx** [comment]
Fixed. It was experimental code, now reverted.
