### ISSUE TITLE
Auto suggest color

### ISSUE THREAD

**Issue by TannerJ07** [david-pfx/PuzzleScriptNext#87]
Check ([ ] -> [x]) all that apply, then describe the issue below:

- [x] I have searched the tracker for similar issues (including closed ones)
- [x] I have provided a detailed example for how this feature should work
- [x] I have provided a use case for this feature, e.g. short description/share link of a game you're making and how you'd use the feature in that game, other things you've tried, edge cases, etc. (if applicable)

In normal Puzzle script, typing bl will suggest blue and black, but it doesn't do that here. Not necessary of course but a nice qol.

**Comment by david-pfx** [comment]
Thanks! I've been kind of waiting for someone to notice the word completion feature was gappy. I didn't know about those gaps, but there are others. Will fix.

**Comment by david-pfx** [comment]
Oops, got it. Off by one. Fixed.
