### ISSUE TITLE
FlickScreen placement

### ISSUE THREAD

**Issue by TannerJ07** [david-pfx/PuzzleScriptNext#88]
**Describe the bug**
Placing objects in with flickscreen on places weird

**Reproduction Steps**
1. Turn flickscreen on (3x3 for this example)
2. Place any object at a position four squares from the left
3. It will be placed one square from the left

**What did you expect would happen?**
It should be place in the visual position of four from the left.

**OS & Browser version, desktop/mobile**
Browser version, Chrome.

**Screenshots, example projects, other relevant issues, etc.**
No screenshot available at the moment. Let me know if it is not reproducible.

**Comment by david-pfx** [comment]
Cannot reproduce. What program were you editing?

**Comment by TannerJ07** [comment]
Program? PS>. Also I cannot demonstrate because the "give puzzlescript next permission" button does not work.

**Comment by david-pfx** [comment]
It works fine on the dev build. https://david-pfx.github.io/PuzzleScriptNext/src/index.html
The stable build has a known problem: the URL is wrong, it should be https://puzzlescriptnext.polyomino.com/auth_pat.html.

**Comment by david-pfx** [comment]
Any progress on this? The share link should work now.
