### ISSUE TITLE
Update documentation: PS Next supports more than 10 colours in sprites

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#91]
> PS Next supports more than 10 colours in sprites
Source: https://github.com/david-pfx/PuzzleScriptNext/issues/90#issuecomment-2315362922

This isn't documented in Documentation/objects.html

What's the implementation? 0-9 then a-z for 36 different colours max? If so I'm happy to provide a pull request for the updated documentation.

**Comment by david-pfx** [comment]
Thanks for the offer, but that's an easy one. Done.
```
    <p>If ten colors really aren't enough, or perhaps you have an automated tool doing subtle shades, then you can use letters for up to another 26 colors. 
      The letter 'a' or 'A' is color index 10, and so on. 
    </p>

```
