### ISSUE TITLE
Document "Show Layers" button

### ISSUE THREAD

**Issue by Draknek** [david-pfx/PuzzleScriptNext#93]
I don't know what it's meant to do, but when I click it all that seems to happen is that the background is drawn on top of every tile

**Comment by david-pfx** [comment]
Experimental.
Set focus on game. Starts showing only level 0. PgUp/PgDn moves up and down the layer stack.
Needs to show the level no (at least). Not as useful as I'd hoped, needs work/rethinking.

**Comment by Draknek** [comment]
Maybe add `(use pgup/pgdn)` to the `Show layers is now ON` console message, so there's some explanation of how it's meant to work?

**Comment by david-pfx** [comment]
For me the big thing is to know which layer you're looking at. And a way to know the names of the objects, and making sure objects are visible. Suddenly it looks like more work.

**Comment by david-pfx** [comment]
Console message and layer no done. Not in docs (for now).
