### ISSUE TITLE
Cursor-down through level-select is limited to 10 levels

### ISSUE THREAD

**Issue by angilbert** [david-pfx/PuzzleScriptNext#94]
**Describe the bug**
If you try and use cursor-down in level-select to reach later levels you stall after 10 levels
This is particularly annoying if you've already solved the first 20 levels and want to reach level 21 (say)

**Reproduction Steps**
Load any game with level-select and more than 10 levels E.g. https://david-pfx.github.io/PuzzleScriptNext/src/play.html?p=3c6b8078c4b48b814fcaa05f09368364. 
Load level-1 and start playing
Go to level-select and use cursor-down to try to reach to level 11 or higher

**What did you expect would happen?**
I could cursor-down to any level

**OS & Browser version, desktop/mobile**
MAC/Chrome - but also seen on ipad
This is particularly a problem on keyboard only games (because on mouse-driven games you can click NEXT)

**Screenshots, example projects, other relevant issues, etc.**
cursor-down here has no effect: 
<img width="567" alt="Screenshot 2024-09-02 at 10 09 36" src="https://github.com/user-attachments/assets/c660e98a-25c2-470c-9311-72fd4cca42a4">

**Comment by angilbert** [comment]
I wondered if this was limitation inherited from PS+ but it seems not. This game works as expected...
https://clickmazes.itch.io/x-marks-the-spot

**Comment by david-pfx** [comment]
Fixed.
